# -*- coding: utf-8 -*-
"""assignment2.ex.v.Q:2.python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sL66CwZHXJeFCxxiYNVziCo9yK7Ty7I1
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.linspace(-2,8,100)
y= x-5
plt.plot(x,y,'r', label = 'y=x-5')
plt.title('graph of y =x-5')
plt.legend(loc = 'upper left')
plt.grid()
plt.show()