# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tX9-93YaRz5vY4w08yqwzgGhguiSxaKM
"""

# Python program to find point that divides
# given line in given ratio.
import numpy as np
import math
import matplotlib.pyplot as plt
x = np.arange(-5,6,1)
y = np.arange(-5,6,1) 
def section(x1, x2, y1, y2, m, n):

# Applying section formula
 x = (float)((n * x1)+(m * x2))/(m + n)
 y = (float)((n * y1)+(m * y2))/(m + n)

# Printing result
 print (x, y)

x1 = 1
x2 =-3
y1 = -2
y2 = 4
m = 2
n = 1
section(x1, x2, y1, y2, m, n)
x = [1,-3]
y = [-2,4]
x0 = [-1.6666]
y0 = [2]
x2= [-0.33]
y2=[0]
plt.show()
for i_x, i_y in zip(x, y):
    plt.text(i_x, i_y, '({}, {})'.format(i_x, i_y))
plt.plot(x, y,x0,y0,x2,y2 ,'ro')
plt.show()